### ISSUE TITLE
我跑出来的结果怎么这么差

### ISSUE THREAD

**Issue by woshilaladui** [cchen-reese/Boundary-Enhanced-NER#13]
![image](https://user-images.githubusercontent.com/26294001/146924720-eb23c21f-83d6-4142-ad4e-37826f1563e8.png)

**Comment by cchen-reese** [comment]
加载字词向量的log截图看下

**Comment by woshilaladui** [comment]
其他东西没动，跑了几次也是这个样子的。。。
![image](https://user-images.githubusercontent.com/26294001/147025211-46b2fad3-096f-4c34-9b0e-69a95b5da311.png)
![image](https://user-images.githubusercontent.com/26294001/147025240-7849b6a5-bd1f-4921-8a9b-897211dc3cfb.png)
![image](https://user-images.githubusercontent.com/26294001/147025261-1546318c-37f2-4695-83f9-b23315042a3f.png)
![image](https://user-images.githubusercontent.com/26294001/147025273-016586d8-b83f-4b92-ac8d-f071cbe94b04.png)
![image](https://user-images.githubusercontent.com/26294001/147025292-713b98b9-1320-4b2f-bacf-ef21ef51f412.png)
![image](https://user-images.githubusercontent.com/26294001/147025307-2147723a-36d6-46b1-8dc5-8109b872b4dd.png)

**Comment by woshilaladui** [comment]
我知道问题所在了，向量弄错了，谢谢。

**Comment by yang20000825** [comment]
你好，请问加载词向量这一步代码你有做什么修改吗？我报错UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 1: invalid start byte了，改成以其他编码读取好像也不行。
