### ISSUE TITLE
关于标注结果的问题，不是每个字符都有一个标签吗？

### ISSUE THREAD

**Issue by t2413** [cchen-reese/Boundary-Enhanced-NER#15]
例如，在test_word_bmes_pos_ddenp.txt 中的第7行 为 “李开复 [POS]NR S-PER.NAM 5 DBL”。这样的话，“李开复”这个整体标注为“S-PER.NAM”，模型测试时，就是对“李开复”这个整体去预测？
但是看了看原本的测试集里，‘李’、‘开’、‘复’ 是分别标注为‘B-PER.NAM’、‘I-PER.NAM’和 ‘E-PER.NAM’的？

**Comment by yang20000825** [comment]
我觉得就是以李开复整体去预测的，因为你看模型的嵌入实际上是word-level的，它无法单独的预测‘李’，‘开’，‘复’。  个人拙见，未必正确。
