### ISSUE TITLE
你好，请教论文中的对比实验

### ISSUE THREAD

**Issue by FreeRotate** [cchen-reese/Boundary-Enhanced-NER#3]
请问你论文中Table1的OntoNotes V4.0实验数据Ma et al.是自己跑的吗？原论文写的F1值是82.81，你论文中写他模型的F1值是75.54？

**Comment by cchen-reese** [comment]
考虑到实验对比的公平性，本文中提到的实验均未使用bert模型，因此Ma et al.的实验数据我们取了无bert且无bi-char的部分。

**Comment by FreeRotate** [comment]
对，我也在想embedding layer加BERT会不会更好
