### ISSUE TITLE
关于使用Weibo数据

### ISSUE THREAD

**Issue by Er1-x** [cchen-reese/Boundary-Enhanced-NER#4]
您好，我将Weibo NER的数据train_word_bmes_pos.txt的数据修改名字后直接放入data文件夹训练报错了，请问需要做什么样的数据预处理嘛？

**Comment by cchen-reese** [comment]
你好，weibo NER的数据需要后续使用DDparser处理，近期我会上传相关语料，具体格式也会写进readme

**Comment by cchen-reese** [comment]
微博数据已放进data文件夹中
