### ISSUE TITLE
function.py里的load_pretrain_emb()是不是有问题啊？

### ISSUE THREAD

**Issue by Tony0726** [cchen-reese/Boundary-Enhanced-NER#7]
elif embedd_dim + 1 != len(tokens):

第一行是个数和维度，所以len(tokens)==2，但是后面都是301个元素，不太对吧

我修改以后，运行程序报了个：

ERROR: LOSS EXPLOSION (>1e8) ! PLEASE SET PROPER PARAMETERS AND STRUCTURE! EXIT....

也不知道到底是哪里的问题

**Comment by cchen-reese** [comment]
对于下载好的emb，需要手动删除第一行（行数和维度），此外这里只能加载word2vec的预训练emb。

**Comment by Tony0726** [comment]
好的，明白了，谢谢（不过文件太大，显示打不开）

**Comment by cchen-reese** [comment]
sed -i '1d' filename

**Comment by cchen-reese** [comment]
linux操作

**Comment by Tony0726** [comment]
好的，不过我看char2vec好像也是这个函数提取

**Comment by Tony0726** [comment]
readme里Conda install pytorch==0.4.1，c小写

**Comment by cchen-reese** [comment]
感谢提醒
